### PR TITLE
Add Cbc_modifyCoefficient to C interface.

### PR DESCRIPTION
**Pull request by jetuk**
As discussed in #655.

I can do the OSI one too if you like?

### CODE REVIEW

**Comment by jjhforrest** [comment]
Does it help you go faster?

Why not do Osi as well

**Comment by jetuk** [comment]
I can not immediately see how this can be achieved through the OSI. I admit I am not familiar with it though.

**Comment by jjhforrest** [comment]
Wait to see if anyone wants to do this from Osi C interface.  If so, I can help.

**Comment by tkralphs** [comment]
I'm not really clear on what Osi C interface we're talking about and why we're waiting for that to be modified first. This looks reasonable to add just as it is.

**Comment by jjhforrest** [comment]
Modified Cbc_C to add modifyCoefficient.  As it calls solver_->modifyCoefficient then Osi needs modifying - done

**Comment by jetuk** [comment]
So, this can be closed?

**Comment by jjhforrest** [comment]
Yes - if it works for you.

**Comment by jetuk** [comment]
Thanks for making the change!

**Pull request closed without merging**
