### PR TITLE
Add CMake based build support on master

### PR DESCRIPTION
**Pull request by Mizux**

### CODE REVIEW

**Comment by ycollet** [comment]
And what about this project ?
https://github.com/ycollet/coinor-cmake/

**Comment by Mizux** [comment]
Didn't know about it, need to check...

But why not integrating CMake files directly in each repository ?

Also it's seems to be based on Cbc complete source tarball than the nowadays github split layout (e.g. coin-or/CoinUtils ...)

And doc seems out of sync
e.g. https://github.com/ycollet/coinor-cmake/blame/master/README.md#L29-L41
Still on Cbc 2.9.9 (also prefer to use `cmake --build build` to be portable (e.g. windows using VS generator you wont have any Makefile...))

**Comment by ycollet** [comment]
You can still compile the Cbc repo using the old way:
```
# Compiling using git repo:

$ git clone https://github.com/ycollet/coinor-cmake.git
$ git clone https://github.com/coin-or/CoinMP.git
$ cd CoinMP
$ git clone https://github.com/coin-or-tools/BuildTools/
$ BuildTools/get.dependencies.sh fetch
$ cp -r ../coinor-cmake/CoinMP .
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/opt/coinmp-devel -DCMAKE_BUILD_TYPE=RELEASE ..
$ make
```

**Comment by Mizux** [comment]
The problem is your script is not windows friendly nor this process is Linux distro package ready IMHO.

Please note this PR is part of this https://github.com/coin-or/CoinUtils/pull/101 (with the same concerns etc...)

**Comment by svigerske** [comment]
As a side-note: The `get.dependencies.sh` in BuildTools will go away sooner or later. The script is now called coinbrew and lives in https://github.com/coin-or/coinbrew/

**Pull request closed without merging**
